<?php

/**
 * @file
 *  Module that enables the attachment of licensing information to arbitrary content
 */

/**
 * Implementation of hook_autoload_info().
 */
function content_license_autoload_info() {
  return array(
    'ContentLicense' => array(
      'file' => 'ContentLicense.inc',
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function content_license_menu() {
  module_load_include('inc', 'content_license');
  return _content_license_menu();
}

/**
 * Menu system wildcard loader for %license
 * allowing licenses to be referenced by id
 *
 * @param int $lid
 * @return stdClass
 */
function license_load($lid) {
  return ContentLicense::load($lid);
}

/**
 * Implementation of hook_theme().
 */
function content_license_theme() {
  module_load_include('inc', 'content_license');
  return _content_license_theme();
}

/**
 * Implementation of hook_form_alter().
 */
function content_license_form_alter(&$form) {
  if ($form['#id'] == 'node-form') {
    if (variable_get('content_license_node_' . $form['#node']->type, FALSE)) {
      module_load_include('inc', 'content_license');
      _content_license_node_form_alter($form);
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 **/
function content_license_nodeapi(&$node, $op, $a3=Null, $page=Null) {
  if (variable_get('content_license_node_' . $node->type, FALSE)) {
    module_load_include('inc', 'content_license');
    return _content_license_nodeapi($node, $op, $a3=Null, $page=Null);
  }
}

/**
 * Page callback that displays information about the available licenses
 */
function _content_license_info() {
  return theme('license_info_page', ContentLicense::load());
}

function _content_license_form_support(&$form) {
  drupal_add_css(drupal_get_path('module', 'content_license') . '/content_license.css');
  return $form;
}